# Generated by Django 3.2.8 on 2021-11-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20211104_1035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='album',
            name='category',
        ),
        migrations.AlterField(
            model_name='album',
            name='album_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
