# Generated by Django 3.2.8 on 2021-11-04 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album', '0003_auto_20211104_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='user',
        ),
        migrations.AlterField(
            model_name='album',
            name='album_subname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.CharField(max_length=30),
        ),
        migrations.RemoveField(
            model_name='album',
            name='up',
        ),
        migrations.AddField(
            model_name='album',
            name='up',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
