# Generated by Django 3.2.8 on 2021-11-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_auto_20211104_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='artist_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_img',
            field=models.ImageField(upload_to='album_cover/upload'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(),
        ),
    ]
